src/proj/urls.py
from django.conf.urls import url
from django.contrib import admin
from f2bmanager import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^managejails/', views.manage_jails, name='managejails'),
	url(r'^addjail/', views.add_jail, name='addjail'),
	url(r'^editjail/', views.edit_jail, name='editjail'),
	url(r'^editdefaultjail/', views.edit_defaultjail, name='editdefaultjail'),
	url(r'^deletejail/', views.delete_jail, name='deletejail'),
	url(r'^viewjail/', views.view_jail, name='viewjail'),
	url(r'^addcustomfilter/', views.add_customfilter, name='addcustomfilter'),
    url(r'^addcustomaction/', views.add_customaction, name='addcustomaction'),
    url(r'^editcustomfilter/', views.edit_customfilter, name='editcustomfilter'),
    url(r'^editcustomaction/', views.edit_customaction, name='editcustomaction'),
    url(r'^viewcustomfilter/', views.view_customfilter, name='viewcustomfilter'),
    url(r'^viewcustomaction/', views.view_customaction, name='viewcustomaction'),
    url(r'^deletecustomfilter/', views.delete_customfilter, name='deletecustomfilter'),
    url(r'^deletecustomaction/', views.delete_customaction, name='deletecustomaction'),
    url(r'^managecustomfilters/', views.manage_customfilters, name='managecustomfilters'),
    url(r'^managecustomactions/', views.manage_customactions, name='managecustomactions'),
	url(r'^addhost/', views.add_host, name='addhost'),
	url(r'^edithost/', views.edit_host, name='edithost'),
	url(r'^managehosts/', views.manage_hosts, name='managehosts'),
	url(r'^deletehost/', views.delete_host, name='deletehost'),
	url(r'^viewlog/', views.view_log, name='viewlog'),
	url(r'^getlog/', views.get_log, name='getlog'),
	url(r'^multiadd/', views.multi_add, name='multiadd'),
	url(r'^logout/', views.logout_view, name='logout'),
	url(r'^deploylocal/', views.deploylocal, name='deploylocal'),
	url(r'^viewloglocal/', views.viewloglocal, name='viewloglocal'),
	url(r'^$', views.home, name='home'),
]

src/f2bmanager/forms.py
from django import forms

from .models import DefaultJail
from .models import Jail
from .models import CustomFilter
from .models import CustomAction
from .models import Host
from .models import Membership

class DefaultJailEditForm(forms.ModelForm):
	ignoreip = forms.CharField(label='Ignore IP', max_length=500, required=False)
	bantime = forms.IntegerField(label='Bantime')
	findtime = forms.IntegerField(label='Findtime')
	maxretry = forms.IntegerField(label='Max Retries')
	# backend = forms.ChoiceField(label='Backend Type', choices=DefaultJail.BACKEND_CHOICE)
	# usedns = forms.ChoiceField(label='Use DNS', choices=DefaultJail.USEDNS_CHOICE)
	class Meta:
		model = DefaultJail
		exclude = []

class JailForm(forms.ModelForm):
	ignoreip = forms.CharField(label='Ignore IP', max_length=500, required=False)
	bantime = forms.IntegerField(label='Bantime')
	findtime = forms.IntegerField(label='Findtime')
	maxretry = forms.IntegerField(label='Max Retries')
	# backend = forms.ChoiceField(label='Backend Type', choices=Jail.BACKEND_CHOICE)
	# usedns = forms.ChoiceField(label='Use DNS', choices=Jail.USEDNS_CHOICE)
	jail_name = forms.CharField(label='Name', max_length=20)
	jail_desc = forms.CharField(label='Description', max_length=500, widget=forms.Textarea(), required=False)
	jail_data = forms.CharField(label='', max_length=1000, widget=forms.Textarea(), required=False)
#	jail_actionvars = forms.CharField(label='Jail Action Variables', max_length=200, widget=forms.Textarea())
	jail_filter = forms.ModelChoiceField(label='Filter', queryset=CustomFilter.objects.all())
	jail_action = forms.ModelChoiceField(label='Action', queryset=CustomAction.objects.all())
	logpath = forms.CharField(label='Log Path', max_length=300)
	enabled = forms.ChoiceField(label='Enable', choices=Jail.ENABLED_CHOICE)
	class Meta:
		model = Jail
		exclude = []

class JailEditForm(forms.Form):
	ignoreip = forms.CharField(label='Ignore IP',max_length=500, required=False)
	bantime = forms.IntegerField(label='Bantime')
	findtime = forms.IntegerField(label='Findtime')
	maxretry = forms.IntegerField(label='Max Retries')
	# backend = forms.ChoiceField(label='Backend Type', choices=Jail.BACKEND_CHOICE)
	# usedns = forms.ChoiceField(label='Use DNS', choices=Jail.USEDNS_CHOICE)
	jail_name = forms.CharField(label='Name', max_length=20)
	jail_desc = forms.CharField(label='Description', max_length=500, required=False, widget=forms.Textarea())
	jail_data = forms.CharField(label='', max_length=1000, widget=forms.Textarea(), required=False)
#	jail_actionvars = forms.CharField(label='Jail Action Variables', max_length=200, widget=forms.Textarea())
	jail_filter = forms.ModelChoiceField(label='Filter', queryset=CustomFilter.objects.all())
	jail_action = forms.ModelChoiceField(label='Action', queryset=CustomAction.objects.all())
	logpath = forms.CharField(label='Log Path', max_length=300)
	enabled = forms.ChoiceField(label='Enable', choices=Jail.ENABLED_CHOICE)

class CustomFilterForm(forms.ModelForm):
	filter_name = forms.CharField(label='Name', max_length=30, widget=forms.TextInput(attrs={'class': "inputtext", 'type': "text"}))
	filter_desc = forms.CharField(label='Description', max_length=500, widget=forms.Textarea(), required=False)
	failregex = forms.CharField(label='Fail Regex', max_length=2000, widget=forms.Textarea())
	ignoreregex = forms.CharField(label='Ignore Regex', max_length=2000, widget=forms.Textarea(), required=False)
	filter_data = forms.CharField(label='Data', max_length=2000, widget=forms.Textarea(), required=False)
	
	class Meta:
		model = CustomFilter
		exclude = []
	def clean_filter_name(self):
		return self.cleaned_data.get('filter_name')
	def clean_filter_desc(self):
		return self.cleaned_data.get('filter_desc')
	def clean_failregex(self):
		a = self.cleaned_data.get('failregex')
		a = a.split('\n')
		b = ''
		for i in a:
			b += i.strip() + '\n            ' 
		return b
	def clean_ignoreregex(self):
		a = self.cleaned_data.get('ignoreregex')
		a = a.split('\n')
		b = ''
		for i in a:
			b += i.strip() + '\n            ' 
		return b
	def clean_filter_data(self):
		return self.cleaned_data.get('filter_data')


class CustomActionForm(forms.ModelForm):
	action_name = forms.CharField(label='Name', max_length=30, widget=forms.TextInput(attrs={'class': "inputtext", 'type': "text"}))
	action_desc = forms.CharField(label='Description', max_length=500, widget=forms.Textarea(), required=False)
	block_type = forms.ChoiceField(label='Block Using', choices=CustomAction.BLOCKTYPE_CHOICE)
	ip_chain = forms.CharField(label='New Chain Name', max_length=100, required=False)
	ip_block_type = forms.ChoiceField(label='Block Type', choices=CustomAction.IPBLOCKTYPE_CHOICE)
	ip_port = forms.CharField(label='Port (# or name)', max_length=30, required=False)
	ip_protocol = forms.ChoiceField(label='Protocol', choices=CustomAction.IPPROTOCOL_CHOICE)
	tcp_file = forms.CharField(label='', max_length=300, required=False)
	tcp_block_type = forms.ChoiceField(label='Block Type', choices=CustomAction.TCPBLOCKTYPE_CHOICE)
	action_data = forms.CharField(label='Data', max_length=2000, widget=forms.Textarea(), required=False)
	
	class Meta:
		model = CustomAction
		exclude = []
	def clean_action_name(self):
		return self.cleaned_data.get('action_name')
	def clean_action_desc(self):
		return self.cleaned_data.get('action_desc')
	def clean_block_type(self):
		return self.cleaned_data.get('block_type')
	def clean_ip_chain(self):
		return self.cleaned_data.get('ip_chain')
	def clean_ip_block_type(self):
		return self.cleaned_data.get('ip_block_type')
	def clean_ip_port(self):
		return self.cleaned_data.get('ip_port')
	def clean_ip_protocol(self):
		return self.cleaned_data.get('ip_protocol')
	def clean_tcp_file(self):
		return self.cleaned_data.get('tcp_file')
	def clean_tcp_block_type(self):
		return self.cleaned_data.get('tcp_block_type')
	def clean_action_data(self):
		return self.cleaned_data.get('action_data')

class CustomFilterEditForm(forms.Form):
	filter_name = forms.CharField(label='Name', max_length=30, widget=forms.TextInput(attrs={'class': "inputtext", 'type': "text"}))
	filter_desc = forms.CharField(label='Description', max_length=500, widget=forms.Textarea(), required=False)
	failregex = forms.CharField(label='Fail Regex', max_length=2000, widget=forms.Textarea())
	ignoreregex = forms.CharField(label='Ignore Regex', max_length=2000, widget=forms.Textarea(), required=False)
	filter_data = forms.CharField(label='Data', max_length=2000, widget=forms.Textarea(), required=False)
	
	def clean_filter_name(self):
		return self.cleaned_data.get('filter_name')
	def clean_filter_desc(self):
		return self.cleaned_data.get('filter_desc')
	def clean_failregex(self):
		a = self.cleaned_data.get('failregex')
		a = a.split('\n')
		b = ''
		for i in a:
			b += i.strip() + '\n            ' 
		return b
	def clean_ignoreregex(self):
		a = self.cleaned_data.get('ignoreregex')
		a = a.split('\n')
		b = ''
		for i in a:
			b += i.strip() + '\n            ' 
		return b
	def clean_filter_data(self):
		return self.cleaned_data.get('filter_data')


class CustomActionEditForm(forms.Form):
	action_name = forms.CharField(label='Name', max_length=30, widget=forms.TextInput(attrs={'class': "inputtext", 'type': "text"}))
	action_desc = forms.CharField(label='Description', max_length=500, widget=forms.Textarea(), required=False)
	block_type = forms.ChoiceField(label='Block Using', choices=CustomAction.BLOCKTYPE_CHOICE)
	ip_chain = forms.CharField(label='New Chain Name', max_length=100, required=False)
	ip_block_type = forms.ChoiceField(label='Block Type', choices=CustomAction.IPBLOCKTYPE_CHOICE)
	ip_port = forms.CharField(label='Port (# or name)', max_length=30, required=False)
	ip_protocol = forms.ChoiceField(label='Protocol', choices=CustomAction.IPPROTOCOL_CHOICE)
	tcp_file = forms.CharField(label='', max_length=300, required=False)
	tcp_block_type = forms.ChoiceField(label='Block Type', choices=CustomAction.TCPBLOCKTYPE_CHOICE)
	action_data = forms.CharField(label='Data', max_length=2000, widget=forms.Textarea(), required=False)
	
	def clean_action_name(self):
		return self.cleaned_data.get('action_name')
	def clean_action_desc(self):
		return self.cleaned_data.get('action_desc')
	def clean_block_type(self):
		return self.cleaned_data.get('block_type')
	def clean_ip_chain(self):
		return self.cleaned_data.get('ip_chain')
	def clean_ip_block_type(self):
		return self.cleaned_data.get('ip_block_type')
	def clean_tcp_file(self):
		return self.cleaned_data.get('tcp_file')
	def clean_tcp_block_type(self):
		return self.cleaned_data.get('tcp_block_type')
	def clean_action_data(self):
		return self.cleaned_data.get('action_data')

class HostForm(forms.ModelForm):
	host_name = forms.CharField(label='Name', max_length=200)
	ip = forms.CharField(label='IP', max_length=30)
	jail = forms.ModelMultipleChoiceField(label='Jails', queryset=Jail.objects.all())
	days = forms.IntegerField(label='Fetch last n days of log')
	class Meta:
		model = Host
		exclude = ['log', 'updated']

class HostEditForm(forms.Form):
	host_name = forms.CharField(label='Name', max_length=200)
	ip = forms.CharField(label='IP', max_length=30)
	jail = forms.ModelMultipleChoiceField(label='Jails', queryset=Jail.objects.all())
	days = forms.IntegerField(label='Fetch last n days of log')

class MultiAddForm(forms.Form):
	host = forms.ModelMultipleChoiceField(label='to the following hosts', queryset=Host.objects.all())
	jail = forms.ModelMultipleChoiceField(label='Add these jails', queryset=Jail.objects.all())

class LoginForm(forms.Form):
	username = forms.CharField(max_length=40,\
		widget=forms.TextInput(attrs={'class':"zocial-dribbble", 'type':"text", 'placeholder':"Username"}))
	password = forms.CharField(max_length=64,\
		widget=forms.PasswordInput(attrs={ 'type':"password", 'placeholder':"Password"}))
	

src/templates/add_action.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>Add new action</title>
		<link type="text/css" rel="stylesheet" href="{% static 'css/action_form.css' %}" /> 

		<link rel="stylesheet" href="{% static 'css/style1.css' %} ">
	</head>
	<body>

		<ul>
  <li><a href="/">Home</a></li>
  <li><a class="active" href="/addcustomaction">ADD ACTION</a></li>
  <li><a href="/addcustomfilter">ADD FILTER</a></li>  
  <li><a href="/managecustomactions">MANAGE ACTIONS</a></li>
  <li><a href="/managecustomfilters">MANAGE FILTERS</a></li>
  <li style="float:right"><a href="/logout">LOG OUT</a></li>
  </ul>

		<div id="wrapper">
			<h1 class="hea"> New Action
			</h1>
			<form method="post" action="" id="actionform" name="actionform" onSubmit="">

				<div class="formElement">
					<!-- <label for="id_action_name">Name</label>
					<input id="id_action_name" name="action_name" class="inputtext" maxlength="50" value="" type="text"/> -->
					{% csrf_token %}
    				{{ form.action_name.label_tag }}
    				{{ form.action_name }}
    				<div id='error1'><i><pre>     (Action already exists!)</pre></i></div>
					<div class="fix"></div>
				</div>

				<div class="formElement">
					<!-- <label for="action_desc">Description</label>
					<textarea id="id_action_desc" name="action_desc"></textarea> -->
					{% csrf_token %}
    				{{ form.action_desc.label_tag }}
    				{{ form.action_desc }}
					<div class="fix"></div>
				</div>

				<div class="formElement">
					<!-- <label for="action_data">Data</label>
					<textarea id="id_action_data" name="action_data"></textarea> -->
					{% csrf_token %}
    				{{ form.action_data.label_tag }}
    				{{ form.action_data }}
					<div class="fix"></div>
				</div>
				{% block submit %}
				<div class="formElement">
					<input type="submit" class="submit" value="Add Action" />
					<div class="fix"></div>
				</div>
				{% endblock %}
				{% block cancel %}
				{% endblock %}
				
			</form>
		</div>
	
	<script type="text/javascript"> var err = {{ name_error }} </script>
	<script type="text/javascript" src="{% static 'js/name_error.js' %}"></script>
	{% block script %}
	{% endblock %}
	</body>
</html>

src/templates/add_customaction.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>Add new action</title>
		<link type="text/css" rel="stylesheet" href="{% static 'css/action_form.css' %}" />
		<link rel="stylesheet" href="{% static "css/style.css" %} "> 
		<link rel="stylesheet" href="{% static 'css/style1.css' %} ">
	</head>
	<body>

		

    <ul>
  <li><a href="/">Home</a></li>
<!--   <li><a href="/addcustomaction">ADD ACTION</a></li>
  <li><a href="/addcustomfilter">ADD FILTER</a></li>  --> 
  <li><a class="active" href="/managecustomactions">MANAGE ACTIONS</a></li>
  <li><a href="/managecustomfilters">MANAGE FILTERS</a></li>
  <li><a href="/managejails">MANAGE JAILS</a></li>
  <li><a href="/managehosts">MANAGE HOSTS</a></li>
  <li style="float:right"><a href="/logout">LOG OUT</a></li>
  </ul>
  <script type="text/javascript" src="{% static 'jquery-3.0.0.min.js' %}"></script>

		<div id="wrapper">
			<h1 class="hea"> New Action
			</h1>
			<form method="post" action="" id="actionform" name="actionform" onSubmit="">

				<div class="formElement">
					<!-- <label for="id_action_name">Name</label>
					<input id="id_action_name" name="action_name" class="inputtext" maxlength="50" value="" type="text"/> -->
					{% csrf_token %}
    				{{ form.action_name.label_tag }}
    				{{ form.action_name }}
    				<div id='error1'><i><pre>     (Action already exists!)</pre></i></div>
					<div class="fix"></div>
				</div>

				<div class="formElement">
					<!-- <label for="action_desc">Description</label>
					<textarea id="id_action_desc" name="action_desc"></textarea> -->
					{% csrf_token %}
    				{{ form.action_desc.label_tag }}
    				{{ form.action_desc }}
					<div class="fix"></div>
				</div>

				<div class="formElement" id="tcpip">
					<!-- <label for="action_desc">Description</label>
					<textarea id="id_action_desc" name="action_desc"></textarea> -->
					{% csrf_token %}
    				{{ form.block_type.label_tag }}
    				{{ form.block_type }}
					<div class="fix"></div>
				</div>

				<div class="formElement bt ip" id="ip1">
					<!-- <label for="action_desc">Description</label>
					<textarea id="id_action_desc" name="action_desc"></textarea> -->
					{% csrf_token %}
    				{{ form.ip_chain.label_tag }}
    				{{ form.ip_chain }}
					<div class="fix"></div>
				</div>

				<div class="formElement bt ip" id="ip2">
					<!-- <label for="action_desc">Description</label>
					<textarea id="id_action_desc" name="action_desc"></textarea> -->
					{% csrf_token %}
    				{{ form.ip_block_type.label_tag }}
    				{{ form.ip_block_type }}
					<div class="fix"></div>
				</div>

				<div class="formElement bt ip" id="ip3">
					<!-- <label for="action_desc">Description</label>
					<textarea id="id_action_desc" name="action_desc"></textarea> -->
					{% csrf_token %}
    				{{ form.ip_port.label_tag }}
    				{{ form.ip_port }}
					<div class="fix"></div>
				</div>

				<div class="formElement bt ip" id="ip4">
					<!-- <label for="action_desc">Description</label>
					<textarea id="id_action_desc" name="action_desc"></textarea> -->
					{% csrf_token %}
    				{{ form.ip_protocol.label_tag }}
    				{{ form.ip_protocol }}
					<div class="fix"></div>
				</div>


				<div class="formElement bt tcp" id="tcp1">
					<!-- <label for="action_desc">Description</label>
					<textarea id="id_action_desc" name="action_desc"></textarea> -->
					{% csrf_token %}
    				{{ form.tcp_block_type.label_tag }}
    				{{ form.tcp_block_type }}
					<div class="fix"></div>
				</div>

				<div class="formElement bt tcp" id="tcp2">
					<!-- <label for="action_desc">Description</label>
					<textarea id="id_action_desc" name="action_desc"></textarea> -->
					{% csrf_token %}
    				{{ form.tcp_file.label_tag }}
    				{{ form.tcp_file }}
					<div class="fix"></div>
				</div>

				<div class="formElement">
					<!-- <label for="action_data">Data</label>
					<textarea id="id_action_data" name="action_data"></textarea> -->
					{% csrf_token %}
    				{{ form.action_data.label_tag }}
    				{{ form.action_data }}
					<div class="fix"></div>
				</div>
				{% block submit %}
				<div class="formElement">
					<input type="submit" class="submit" value="Add Action" />
					<div class="fix"></div>
				</div>
				{% endblock %}
				{% block cancel %}
				{% endblock %}
				
			</form>
		</div>
	
	<script type="text/javascript"> var err = {{ name_error }} </script>
	<script type="text/javascript" src="{% static 'js/name_error.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/actionblocktype.js' %}"></script>
	{% block script %}
	{% endblock %}
	</body>
</html>

src/templates/add_host.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form method="post" action="" onSubmit="">
{% csrf_token %}
{{form}}
<div>
	<input type="submit" value="Add Host" />
</div>
</form>
</body>
</html>

src/templates/add_jail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link type="text/css" rel="stylesheet" href="{% static 'css/style1.css' %}" /> 
	<link type="text/css" rel="stylesheet" href="{% static 'css/style2.css' %}" /> 

	

</head>
<body>

<ul>
  <li><a href="/">Home</a></li>
<!--   <li><a href="/addcustomaction">ADD ACTION</a></li>
  <li><a href="/addcustomfilter">ADD FILTER</a></li>   -->
  <li><a href="/managecustomactions">MANAGE ACTIONS</a></li>
  <li><a href="/managecustomfilters">MANAGE FILTERS</a></li>
  <li><a class="active" href="/managejails">MANAGE JAILS</a></li>
  <li><a href="/managehosts">MANAGE HOSTS</a></li>
  <li style="float:right"><a href="/logout">LOG OUT</a></li>
  </ul>



<form method="post" action="" onSubmit="">
{% csrf_token %}
{{ form.ignoreip.label_tag }}
{{ form.ignoreip }}
 
{{ form.bantime.label_tag }}
{{ form.bantime }}
 
{{ form.findtime.label_tag }}
{{ form.findtime }}
 
{{ form.maxretry.label_tag }}
{{ form.maxretry }}
 
{{ form.backend.label_tag }}
{{ form.backend }}
 
{{ form.usedns.label_tag }}
{{ form.usedns }}
 
{{ form.jail_name.label_tag }}
{{ form.jail_name }}
 
{{ form.jail_desc.label_tag }}
{{ form.jail_desc }}
 
{{ form.jail_data.label_tag }}
{{ form.jail_data }}
 
{{ form.jail_filter.label_tag }}
{{ form.jail_filter }}
 
{{ form.jail_action.label_tag }}
{{ form.jail_action }}
 
{{ form.logpath.label_tag }}
{{ form.logpath }}
 
{{ form.enabled.label_tag }}
{{ form.enabled }}
<div>
	<input type="submit" value="Add Jail" />
</div>
</form>
</body>
</html>

src/templates/edit_customaction.html
{% extends "add_customaction.html" %}

{% block submit %}
<div class="formElement">
	<input type="submit" class="submit" value="Save" />
</div>
{% endblock %}

{% block cancel %}
<div class="formElement">
	<input type="button" onclick="window.location.replace(&quot;http://127.0.0.1:8000&quot;)" class="submit" id="cancel" value="Cancel" />
</div>
{% endblock %}

{% block script %}
	<script type="text/javascript">
	</script>
{% endblock %}

src/templates/edit_customfilter.html
{% extends "add_customfilter.html" %}

{% block submit %}
<div class="formElement">
	<input type="submit" class="submit" value="Save" />
</div>
{% endblock %}

{% block cancel %}
<div class="formElement">
	<input type="button" onclick="window.location.replace(&quot;http://127.0.0.1:8000&quot;)" class="submit" id="cancel" value="Cancel" />
</div>
{% endblock %}

{% block script %}
	<script type="text/javascript">
	</script>
{% endblock %}

src/templates/edit_host.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form method="post" action="" onSubmit="">
{% csrf_token %}
 {{form}} 
<div>
	<input type="submit" value="Save Changes" />
</div>
</form>
</body>
</html>

src/templates/edit_jail.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<ul>
  <li><a href="/">Home</a></li>
 <!--  <li><a href="/addcustomaction">ADD ACTION</a></li>
  <li><a class="active" href="/addcustomfilter">ADD FILTER</a></li>   -->
  <li><a href="/managecustomactions">MANAGE ACTIONS</a></li>
  <li><a href="/managecustomfilters">MANAGE FILTERS</a></li>
    <li><a href="/managejails">MANAGE JAILS</a></li>
  <li><a href="/managehosts">MANAGE HOSTS</a></li>
  <li style="float:right"><a href="/logout">LOG OUT</a></li>
  </ul>
<form method="post" action="" onSubmit="">
{% csrf_token %}
{{form}}
<div>
	<input type="submit" value="Save Changes" />
</div>
</form>
</body>
</html>

src/templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>F2B manager</title>
    <!-- <script src="http://s.codepen.io/assets/libs/modernizr.js" type="text/javascript"></script> -->


    
    
    
        <link rel="stylesheet" href="{% static "css/style.css" %} ">
        <link rel="stylesheet" href="{% static "css/style1.css" %} ">

    
    
    
  </head>

  <body>

<!--   <ul>
  <li><a class="active" href="/">Home</a></li>
  <li><a href="/addaction">ADD ACTION</a></li>
  <li><a href="/addfilter">ADD FILTER</a></li>  
  <li><a href="/manageactions">MANAGE ACTIONS</a></li>
  <li><a href="/managefilters">MANAGE FILTERS</a></li>
  </ul> -->

    <h1>Login Form </h1>

<!-- <div class="stand"> -->
  <!-- <div class="outer-screen"> -->
    <div class="inner-screen">
      <div class="form">
      <form method="post">
<!--         <input type="text" class="zocial-dribbble" placeholder="Username" />
        <input type="text" placeholder="Password" /> -->
        {% csrf_token %}
        {{form.username }}
        {{form.password }}
         <input type="submit" value="Login" />
      </form>
        <a href="">Lost your password?</a>
      </div> 
    </div> 
<!--   </div>  -->
<!-- </div> -->
   <!--  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
 -->
    
    
    
    
  </body>
</html>

src/templates/multi_add.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form method="post" action="" onSubmit="">
{% csrf_token %}
{{ form.jail.label_tag }}
{{ form.jail }}
{{ form.host.label_tag }}
{{ form.host }}
<div>
	<input type="submit" value="Add" />
</div>
</form>
</body>
</html>